server:
   port: 8001
spring:
 application:
    name: accound_cmd
 data:
    mongodb:
      host: localhost
      port: 27017
      database: bankAccount
 jpa:
  show-sql: 'true'
  hibernate:
    ddl-auto: create-drop
 kafka:
    producer:
      bootstrap-servers:
      - localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        
springdoc:
  swagger-ui:
    path: /swagger-ui.html      
        